
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c69fb9bc-35e2-4849-a083-e3ef9dd010fb";
      fsType = "ext4";
    };

  fileSystems."/run/media/toby/games/" =
    { device = "/dev/disk/by-uuid/98276471-ab17-4375-9189-c3f0db3093e4";
      fsType = "ext4";
      mountPoint = "/run/media/toby/games";
    };


  fileSystems."/run/media/toby/coding/" =
    { device = "/dev/disk/by-uuid/96bb14bc-082b-48d0-ae6d-d0c3f1a54239";
      fsType = "ext4";
      mountPoint = "/run/media/toby/coding";
    };

   fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/97BE-F7EC";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
